# Generated by Django 5.0.6 on 2024-05-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0005_userdata_alter_job_user_delete_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User Data'},
        ),
    ]
