# Generated by Django 5.0.6 on 2024-05-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0007_rename_user_job_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user_id',
            new_name='user',
        ),
    ]
