# Generated by Django 5.0.6 on 2024-05-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0008_rename_user_id_job_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='client',
        ),
    ]
