# Generated by Django 5.0.6 on 2024-05-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0009_rename_user_job_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='client',
            new_name='user',
        ),
    ]
