# Generated by Django 5.0.6 on 2024-06-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0011_alter_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='street_address',
        ),
    ]
