# Generated by Django 5.0.6 on 2024-12-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0012_remove_userdata_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
