# Generated by Django 5.0.6 on 2024-12-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0014_alter_job_user_delete_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='userId',
        ),
    ]
