# Generated by Django 5.0.6 on 2024-12-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0015_rename_user_job_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='l', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='username',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='zipCode',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
