# Generated by Django 5.1.4 on 2024-12-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0016_job_city_job_state_job_username_job_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='zipCode',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
