# Generated by Django 5.1.4 on 2025-01-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0017_alter_job_description_alter_job_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
