# Generated by Django 5.1.4 on 2025-01-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0018_alter_job_description_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='joinedData',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
