# Generated by Django 5.1.4 on 2025-01-08 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0021_savedjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobs',
            name='jobs',
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='created_at',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='date_joined',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='pay',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='username',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='zipCode',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_joined',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='username',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='savedjobs',
            name='userId',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
