# Generated by Django 5.1.4 on 2025-01-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0022_remove_savedjobs_jobs_savedjobs_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='mainUserId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
