# Generated by Django 5.1.4 on 2025-01-08 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0023_savedjobs_mainuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='saved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
