# Generated by Django 5.1.4 on 2025-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidegig', '0027_rename_messsage_jobmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmessage',
            name='recipientId',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
